/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package widows;

import java.sql.*;
import class_systems.Conexion;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author andre
 */
public class BrandsGraphics extends javax.swing.JFrame {

    String user;
    int[] vector_brands_total = new int[11];
    String[] vector_brands_name = new String[11];

    int hp;
    int lenovo;
    int dell;
    int acer;
    int apple;
    int toshiba;
    int brother;
    int samsung;
    int asus;
    int alienware;
    int xerox;

    /**
     * Creates new form StatusGrapichs
     */
    public BrandsGraphics() {
        initComponents();

        user = Login.user;
        setSize(550, 450);
        setResizable(false);
        setTitle("Technical - Session as " + user);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(
                jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(),
                Image.SCALE_DEFAULT)
        );
        jLabel_Wallpaper.setIcon(icon);
        this.repaint();

        repaint();

        try {
            Connection cn = Conexion.connect();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT brand, COUNT(brand) AS Brands FROM equipments GROUP BY brand"
            );
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                int position = 0;
                do {
                    vector_brands_name[position] = rs.getString(1);
                    vector_brands_total[position] = rs.getInt(2);

                    if (vector_brands_name[position].equalsIgnoreCase("Acer")) {
                        acer = vector_brands_total[position];
                    } else if (vector_brands_name[position].equalsIgnoreCase("Alienware")) {
                        alienware = vector_brands_total[position];
                    } else if (vector_brands_name[position].equalsIgnoreCase("Apple")) {
                        apple = vector_brands_total[position];
                    } else if (vector_brands_name[position].equalsIgnoreCase("Asus")) {
                        asus = vector_brands_total[position];
                    } else if (vector_brands_name[position].equalsIgnoreCase("Brother")) {
                        brother = vector_brands_total[position];
                    } else if (vector_brands_name[position].equalsIgnoreCase("Dell")) {
                        dell = vector_brands_total[position];
                    } else if (vector_brands_name[position].equalsIgnoreCase("HP")) {
                        hp = vector_brands_total[position];
                    } else if (vector_brands_name[position].equalsIgnoreCase("Lenovo")) {
                        lenovo = vector_brands_total[position];
                    } else if (vector_brands_name[position].equalsIgnoreCase("Samsung")) {
                        samsung = vector_brands_total[position];
                    } else if (vector_brands_name[position].equalsIgnoreCase("Toshiba")) {
                        toshiba = vector_brands_total[position];
                    } else if (vector_brands_name[position].equalsIgnoreCase("Xerox")) {
                        xerox = vector_brands_total[position];
                    }

                    position++;
                } while (rs.next());
            }
        } catch (SQLException e) {
            System.err.println("Error when querying " + e);
            JOptionPane.showMessageDialog(null, "Error data querying. Contact with admin.");
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Status Graphic");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrandsGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrandsGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrandsGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrandsGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrandsGraphics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint(Graphics g) {
        super.paint(g);

        int total_brands = acer + alienware + apple + asus + brother + dell + hp + lenovo + samsung + toshiba + xerox;

        int grades_acer = acer * 360 / total_brands;
        int grades_alienware = alienware * 360 / total_brands;
        int grades_apple = apple * 360 / total_brands;
        int grades_asus = asus * 360 / total_brands;
        int grades_brother = brother * 360 / total_brands;
        int grades_dell = dell * 360 / total_brands;
        int grades_hp = hp * 360 / total_brands;
        int grades_lenovo = lenovo * 360 / total_brands;
        int grades_samsung = samsung * 360 / total_brands;
        int grades_toshiba = toshiba * 360 / total_brands;
        int grades_xeros = xerox * 360 / total_brands;

        //Brnad Acer
        g.setColor(new Color(175, 122, 197));//purple
        g.fillArc(25, 100, 270, 270, 0, grades_acer);
        g.fillRect(310, 120, 20, 20);
        g.drawString(acer + " Acer", 340, 135);

        //Brnad Alienware
        g.setColor(new Color(0, 255, 0));//green
        g.fillArc(25, 100, 270, 270, grades_acer, grades_alienware);
        g.fillRect(310, 150, 20, 20);
        g.drawString(alienware + " Alienware", 340, 165);

        //Brnad Apple
        g.setColor(new Color(0, 255, 255));//water green
        g.fillArc(25, 100, 270, 270, grades_acer + grades_alienware, grades_apple);
        g.fillRect(310, 180, 20, 20);
        g.drawString(apple + " Apple", 340, 195);

        //Brnad Asus
        g.setColor(new Color(55, 0, 255));//blue
        g.fillArc(25, 100, 270, 270, grades_acer + grades_alienware + grades_apple, grades_asus);
        g.fillRect(310, 210, 20, 20);
        g.drawString(asus + " Asus", 340, 225);

        //Brnad Brother
        g.setColor(new Color(255, 255, 255));//white
        g.fillArc(25, 100, 270, 270, grades_acer + grades_alienware + grades_apple + grades_asus, grades_brother);
        g.fillRect(310, 240, 20, 20);
        g.drawString(brother + " Brother", 340, 255);

        //Brnad Dell
        g.setColor(new Color(247, 220, 111));//navy blue
        g.fillArc(25, 100, 270, 270, grades_acer + grades_alienware + grades_apple + grades_asus + grades_brother, grades_dell);
        g.fillRect(310, 270, 20, 20);
        g.drawString(dell + " Dell", 340, 285);

        //Brnad HP
        g.setColor(new Color(21, 42, 160));//yellow
        g.fillArc(25, 100, 270, 270, grades_acer + grades_alienware + grades_apple + grades_asus + grades_brother + grades_dell, grades_hp);
        g.fillRect(310, 300, 20, 20);
        g.drawString(hp + " HP", 340, 315);

        //Brnad Lenovo
        g.setColor(new Color(215, 96, 0));//orange
        g.fillArc(25, 100, 270, 270, grades_acer + grades_alienware + grades_apple + grades_asus + grades_brother + grades_dell + grades_hp, grades_lenovo);
        g.fillRect(310, 330, 20, 20);
        g.drawString(lenovo + " Lenovo", 340, 345);

        //Brnad Samsung
        g.setColor(new Color(215, 96, 140));//pink
        g.fillArc(25, 100, 270, 270, grades_acer + grades_alienware + grades_apple + grades_asus + grades_brother + grades_dell + grades_hp + grades_lenovo, grades_samsung);
        g.fillRect(430, 120, 20, 20);
        g.drawString(samsung + " Samsung", 460, 135);

        //Brnad Toshiba
        g.setColor(new Color(215, 196, 25));//yellow canario
        g.fillArc(25, 100, 270, 270, grades_acer + grades_alienware + grades_apple + grades_asus + grades_brother + grades_dell + grades_hp + grades_lenovo + grades_samsung, grades_toshiba);
        g.fillRect(430, 150, 20, 20);
        g.drawString(toshiba + " Toshiba", 460, 165);

        //Brnad Xeros
        g.setColor(new Color(93, 173, 226));//yellow canario
        g.fillArc(25, 100, 270, 270, grades_acer + grades_alienware + grades_apple + grades_asus + grades_brother + grades_dell + grades_hp + grades_lenovo + grades_samsung + grades_toshiba, grades_xeros);
        g.fillRect(430, 180, 20, 20);
        g.drawString(xerox + " Xeros", 460, 195);
    }
}
