/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package widows;

import java.sql.*;
import class_systems.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author andre
 */
public class EquipmentInformationTechnical extends javax.swing.JFrame {

    int id_Equipment = 0;
    String user = "";

    /**
     * Creates new form EquipmentInformation
     */
    public EquipmentInformationTechnical() {
        initComponents();
        user = Login.user;
        id_Equipment = ManageEquipments.idEquipment_update;

        try {
            Connection cn = Conexion.connect();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT * FROM equipments WHERE id_equipment = '" + id_Equipment + "'"
            );
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                cmb_TypeEquipment.setSelectedItem(rs.getString("equipment_type"));
                cmb_Brand.setSelectedItem(rs.getString("brand"));
                cmb_status.setSelectedItem(rs.getString("status"));
                txt_Model.setText(rs.getString("model"));
                txt_NumberSerie.setText(rs.getString("number_serie"));
                txt_LastModify.setText(rs.getString("last_modify"));

                String day = "";
                String month = "";
                String year = "";

                day = rs.getString("day_admission");
                month = rs.getString("month_admission");
                year = rs.getString("age_admission");

                txt_Date.setText(day + "/" + month + "/" + year);

                jTextPane_Observations.setText(rs.getString("observations"));
                jTextPane_TechnicalCommenst.setText(rs.getString("technical_comments"));
                jLabel_RevisionTechnicalBy.setText("Comments and news of Technical: " + rs.getString("rechnical_revision_of"));
            }
        } catch (SQLException e) {
            System.err.println("Error querying equipment information " + e);
        }

        setTitle("Equipment registerd with ID " + id_Equipment + " - Session as " + user);
        setSize(670, 530);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(
                jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(),
                Image.SCALE_DEFAULT)
        );
        jLabel_Wallpaper.setIcon(icon);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_title = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_name1 = new javax.swing.JLabel();
        jLabel_name2 = new javax.swing.JLabel();
        jLabel_name3 = new javax.swing.JLabel();
        jLabel_name4 = new javax.swing.JLabel();
        jLabel_name5 = new javax.swing.JLabel();
        jLabel_name6 = new javax.swing.JLabel();
        jLabel_name7 = new javax.swing.JLabel();
        jLabel_name8 = new javax.swing.JLabel();
        jLabel_RevisionTechnicalBy = new javax.swing.JLabel();
        txt_CustomerName = new javax.swing.JTextField();
        txt_Model = new javax.swing.JTextField();
        txt_NumberSerie = new javax.swing.JTextField();
        txt_LastModify = new javax.swing.JTextField();
        txt_Date = new javax.swing.JTextField();
        cmb_TypeEquipment = new javax.swing.JComboBox<>();
        cmb_Brand = new javax.swing.JComboBox<>();
        cmb_status = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_Observations = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane_TechnicalCommenst = new javax.swing.JTextPane();
        jButton_Update = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title.setText("Equipment Information");
        getContentPane().add(jLabel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name.setText("Customer Name:");
        getContentPane().add(jLabel_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel_name1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name1.setText("Type Equipment");
        getContentPane().add(jLabel_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel_name2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name2.setText("Brand:");
        getContentPane().add(jLabel_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel_name3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name3.setText("Model:");
        getContentPane().add(jLabel_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel_name4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name4.setText("Number Serie:");
        getContentPane().add(jLabel_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel_name5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name5.setText("Date of Entry");
        getContentPane().add(jLabel_name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jLabel_name6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name6.setText("Last Modify By:");
        getContentPane().add(jLabel_name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel_name7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name7.setText("Status:");
        getContentPane().add(jLabel_name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel_name8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name8.setText("Damage Report and Observations:");
        getContentPane().add(jLabel_name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel_RevisionTechnicalBy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_RevisionTechnicalBy.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_RevisionTechnicalBy.setText("Comments And Updates Technical");
        getContentPane().add(jLabel_RevisionTechnicalBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        txt_CustomerName.setBackground(new java.awt.Color(153, 153, 255));
        txt_CustomerName.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_CustomerName.setForeground(new java.awt.Color(255, 255, 255));
        txt_CustomerName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_CustomerName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_CustomerName.setEnabled(false);
        getContentPane().add(txt_CustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        txt_Model.setBackground(new java.awt.Color(153, 153, 255));
        txt_Model.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Model.setForeground(new java.awt.Color(255, 255, 255));
        txt_Model.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Model.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_Model, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, -1));

        txt_NumberSerie.setBackground(new java.awt.Color(153, 153, 255));
        txt_NumberSerie.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_NumberSerie.setForeground(new java.awt.Color(255, 255, 255));
        txt_NumberSerie.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_NumberSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_NumberSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 210, -1));

        txt_LastModify.setBackground(new java.awt.Color(153, 153, 255));
        txt_LastModify.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_LastModify.setForeground(new java.awt.Color(255, 255, 255));
        txt_LastModify.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_LastModify.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_LastModify.setEnabled(false);
        getContentPane().add(txt_LastModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 210, -1));

        txt_Date.setBackground(new java.awt.Color(153, 153, 255));
        txt_Date.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Date.setForeground(new java.awt.Color(255, 255, 255));
        txt_Date.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Date.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_Date.setEnabled(false);
        getContentPane().add(txt_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 180, -1));

        cmb_TypeEquipment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Print", "Multifunctional" }));
        getContentPane().add(cmb_TypeEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, -1));

        cmb_Brand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Alienware", "Apple", "Asus", "Brother", "Dell", "HP", "Lenovo", "Samsung", "Toshiba", "Xerox" }));
        getContentPane().add(cmb_Brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, -1));

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New Admission", "Not Fixed", "In Review", "Fixed", "Delivered", " " }));
        getContentPane().add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 130, -1));

        jTextPane_Observations.setEditable(false);
        jScrollPane1.setViewportView(jTextPane_Observations);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 330, 120));

        jScrollPane2.setViewportView(jTextPane_TechnicalCommenst);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 330, 120));

        jButton_Update.setBackground(new java.awt.Color(153, 153, 255));
        jButton_Update.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_Update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Update.setText("Comment and Update");
        jButton_Update.setBorder(null);
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 210, 35));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        String status;
        String technicalComments;
        String technical;

        status = cmb_status.getSelectedItem().toString();
        technicalComments = jTextPane_TechnicalCommenst.getText();
        technical = user;

        try {
            Connection cn = Conexion.connect();
            PreparedStatement pst = cn.prepareStatement(
                    "UPDATE equipments SET status = ?, technical_comments = ?, rechnical_revision_of = ? "
                    + "WHERE id_equipment = '" + id_Equipment + "'"
            );
            
            pst.setString(1, status);
            pst.setString(2, technicalComments);
            pst.setString(3, technical);
            
            pst.executeUpdate();
            cn.close();
            
            JOptionPane.showMessageDialog(null, "Successful Update");
            this.dispose();
        } catch (SQLException e) {
            System.err.println("Error updating the equipment " + e);
            JOptionPane.showMessageDialog(null, "Error updating the equipment, contact with admin.");
        }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquipmentInformationTechnical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquipmentInformationTechnical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquipmentInformationTechnical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquipmentInformationTechnical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EquipmentInformationTechnical().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_Brand;
    private javax.swing.JComboBox<String> cmb_TypeEquipment;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel_RevisionTechnicalBy;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_name1;
    private javax.swing.JLabel jLabel_name2;
    private javax.swing.JLabel jLabel_name3;
    private javax.swing.JLabel jLabel_name4;
    private javax.swing.JLabel jLabel_name5;
    private javax.swing.JLabel jLabel_name6;
    private javax.swing.JLabel jLabel_name7;
    private javax.swing.JLabel jLabel_name8;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane_Observations;
    private javax.swing.JTextPane jTextPane_TechnicalCommenst;
    private javax.swing.JTextField txt_CustomerName;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_LastModify;
    private javax.swing.JTextField txt_Model;
    private javax.swing.JTextField txt_NumberSerie;
    // End of variables declaration//GEN-END:variables

    public void Clear() {
        txt_CustomerName.setText("");
        txt_Date.setText("");
        txt_Model.setText("");
        txt_NumberSerie.setText("");
        jTextPane_Observations.setText("");
    }
}
