/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package widows;

import java.sql.*;
import class_systems.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author andre
 */
public class RestorePassword extends javax.swing.JFrame {

    String user = "";
    String user_update;

    /**
     * Creates new form RestorePassword
     */
    public RestorePassword() {
        initComponents();
        user = Login.user;
        user_update = ManageUsers.user_update;

        setSize(360, 260);
        setResizable(false);
        setTitle("Change Password as " + user_update);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(
                jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(),
                Image.SCALE_DEFAULT)
        );
        jLabel_Wallpaper.setIcon(icon);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_restorePassword = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        txt_confimPassword = new javax.swing.JPasswordField();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Change Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jButton_restorePassword.setBackground(new java.awt.Color(153, 153, 255));
        jButton_restorePassword.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_restorePassword.setForeground(new java.awt.Color(255, 255, 255));
        jButton_restorePassword.setText("Restore Password");
        jButton_restorePassword.setBorder(null);
        jButton_restorePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_restorePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_restorePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, 35));

        txt_password.setBackground(new java.awt.Color(153, 153, 255));
        txt_password.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_confimPassword.setBackground(new java.awt.Color(153, 153, 255));
        txt_confimPassword.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_confimPassword.setForeground(new java.awt.Color(255, 255, 255));
        txt_confimPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_confimPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_confimPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_restorePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_restorePasswordActionPerformed
        String password;
        String confim_password;
        
        password = txt_password.getText().trim();
        confim_password = txt_confimPassword.getText().trim();
        
        if (!password.equals("") && !confim_password.equals("")) {
            if (password.equals(confim_password)) {
                try {
                    Connection cn = Conexion.connect();
                    PreparedStatement pst = cn.prepareStatement(
                            "UPDATE users SET password = ? WHERE username = '" + user_update + "'"
                    );
                    pst.setString(1, password);
                    pst.executeUpdate();
                    
                    cn.close();
                    
                    txt_password.setBackground(Color.green);
                    txt_confimPassword.setBackground(Color.green);
                    
                    JOptionPane.showMessageDialog(null, "Password changed.");
                } catch (SQLException e) {
                    System.err.println("Password reset error. " + e);
                }
            } else {
                txt_confimPassword.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "The password must be the same.");
            }
        } else {
            txt_password.setBackground(Color.red);
            txt_confimPassword.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "The password cannot be empty.");
        }
    }//GEN-LAST:event_jButton_restorePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestorePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestorePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestorePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestorePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestorePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_restorePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JPasswordField txt_confimPassword;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
