/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package widows;

import java.sql.*;
import class_systems.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author andre
 */
public class UserInformation extends javax.swing.JFrame {

    String user = "";
    String user_update = "";
    int id;

    /**
     * Creates new form UserInformation
     */
    public UserInformation() {
        initComponents();
        user = Login.user;
        user_update = ManageUsers.user_update;

        setSize(630, 450);
        setResizable(false);
        setTitle("User Information " + user_update + " - Session as " + user);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(
                jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(),
                Image.SCALE_DEFAULT)
        );
        jLabel_Wallpaper.setIcon(icon);
        this.repaint();

        jLabel_title.setText("User Information " + user_update);

        try {
            Connection cn = Conexion.connect();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT * FROM users WHERE username = '" + user_update + "'"
            );
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                id = rs.getInt("id_user");

                txt_name.setText(rs.getString("user_name"));
                txt_email.setText(rs.getString("email"));
                txt_phone.setText(rs.getString("phone"));
                txt_username.setText(rs.getString("username"));
                txt_registerby.setText(rs.getString("register_by"));

                cmb_levels.setSelectedItem(rs.getString("type_level"));
                cmb_status.setSelectedItem(rs.getString("status"));
            }

            cn.close();
        } catch (SQLException e) {
            System.err.println("Error loading user, " + e);
            JOptionPane.showMessageDialog(null, "Error loading, contact with admin.");
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_title = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_name1 = new javax.swing.JLabel();
        jLabel_name2 = new javax.swing.JLabel();
        jLabel_name3 = new javax.swing.JLabel();
        jLabel_name4 = new javax.swing.JLabel();
        jLabel_name5 = new javax.swing.JLabel();
        jLabel_name6 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_registerby = new javax.swing.JTextField();
        cmb_status = new javax.swing.JComboBox<>();
        cmb_levels = new javax.swing.JComboBox<>();
        jButton_update = new javax.swing.JButton();
        jButton_restorePassword = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title.setText("User Information");
        getContentPane().add(jLabel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name.setText("Name:");
        getContentPane().add(jLabel_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel_name1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name1.setText("Email:");
        getContentPane().add(jLabel_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel_name2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name2.setText("Phone:");
        getContentPane().add(jLabel_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel_name3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name3.setText("Permission as:");
        getContentPane().add(jLabel_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel_name4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name4.setText("Username:");
        getContentPane().add(jLabel_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel_name5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name5.setText("Status:");
        getContentPane().add(jLabel_name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel_name6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_name6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name6.setText("Registered by:");
        getContentPane().add(jLabel_name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        txt_name.setBackground(new java.awt.Color(153, 153, 255));
        txt_name.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_email.setBackground(new java.awt.Color(153, 153, 255));
        txt_email.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        txt_phone.setBackground(new java.awt.Color(153, 153, 255));
        txt_phone.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_phone.setForeground(new java.awt.Color(255, 255, 255));
        txt_phone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_phone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

        txt_username.setBackground(new java.awt.Color(153, 153, 255));
        txt_username.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

        txt_registerby.setBackground(new java.awt.Color(153, 153, 255));
        txt_registerby.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_registerby.setForeground(new java.awt.Color(255, 255, 255));
        txt_registerby.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_registerby.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_registerby.setEnabled(false);
        getContentPane().add(txt_registerby, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, -1));

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On", "Off" }));
        getContentPane().add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 210, -1));

        cmb_levels.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Capturist", "Technical" }));
        getContentPane().add(cmb_levels, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, -1));

        jButton_update.setBackground(new java.awt.Color(153, 153, 255));
        jButton_update.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setText("Update User");
        jButton_update.setBorder(null);
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 210, 35));

        jButton_restorePassword.setBackground(new java.awt.Color(153, 153, 255));
        jButton_restorePassword.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_restorePassword.setForeground(new java.awt.Color(255, 255, 255));
        jButton_restorePassword.setText("Restore Password");
        jButton_restorePassword.setBorder(null);
        getContentPane().add(jButton_restorePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 210, 35));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed

        int permission_cmb;
        int status_cmb;
        int validation = 0;
        String name;
        String username;
        String email;
        String phone;
        String password;
        String permission_string = "";
        String status_string = "";

        email = txt_email.getText().trim();
        username = txt_username.getText().trim();
        name = txt_name.getText().trim();
        phone = txt_phone.getText().trim();
        permission_cmb = cmb_levels.getSelectedIndex() + 1;
        status_cmb = cmb_status.getSelectedIndex() + 1;

        if (email.equals("")) {
            txt_email.setBackground(Color.red);
            validation++;
        }

        if (username.equals("")) {
            txt_username.setBackground(Color.red);
            validation++;
        }

        if (name.equals("")) {
            txt_name.setBackground(Color.red);
            validation++;
        }

        if (phone.equals("")) {
            txt_phone.setBackground(Color.red);
            validation++;
        }

        if (validation == 0) {
            if (permission_cmb == 1) {
                permission_string = "Admin";
            } else if (permission_cmb == 2) {
                permission_string = "Capturist";
            } else {
                permission_string = "Technical";
            }

            if (status_cmb == 1) {
                status_string = "On";
            } else {
                status_string = "Off";
            }

            try {
                Connection cn = Conexion.connect();
                PreparedStatement pst = cn.prepareStatement(
                        "SELECT username FROM users WHERE username = '" + username + "' AND NOT id_user = '" 
                                + id + "'"
                );
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    txt_username.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Username not avaliable.");

                    cn.close();
                } else {
                    Connection cn2 = Conexion.connect();
                    PreparedStatement pst2 = cn2.prepareStatement(
                            "UPDATE users SET user_name=?, email=?, phone=?, username=?, type_level=?, status=?"
                            + "WHERE id_user = '" + id + "'"
                    );
                    pst2.setString(1, name );
                    pst2.setString(2, email);
                    pst2.setString(3, phone);
                    pst2.setString(4, username);
                    pst2.setString(5, permission_string);
                    pst2.setString(6, status_string);
                    
                    pst2.executeUpdate();
                    cn.close();
                    
                    JOptionPane.showMessageDialog(null, "Update Successful");
                }
            } catch (SQLException e) {
                System.err.println("Error updating " + e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "You must fill all the fields.");
        }

        try {

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_levels;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JButton jButton_restorePassword;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_name1;
    private javax.swing.JLabel jLabel_name2;
    private javax.swing.JLabel jLabel_name3;
    private javax.swing.JLabel jLabel_name4;
    private javax.swing.JLabel jLabel_name5;
    private javax.swing.JLabel jLabel_name6;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_registerby;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
